import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import Modal from "../components/modal";
import { FormWrapper } from "../components/new/wrapper";
import { HOMEPAGE_LINKS as links } from "../data";

const Home: NextPage = () => {
  const [isTitleHovered, setIsTitleHovered] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <h1
          onMouseEnter={() => setIsTitleHovered(true)}
          onMouseLeave={() => setIsTitleHovered(false)}
          className={`${
            isTitleHovered ? "text-3xl" : "text-5xl "
          } text-center font-extrabold tracking-tight text-white transition-all duration-500 sm:text-[5rem]`}
        >
          <span className="text-[hsl(280,100%,70%)]">
            D
            {isTitleHovered && (
              <span className=" transition-all duration-200 ease-in-out">
                entralized
              </span>
            )}
          </span>
          -Warden
        </h1>

        <p className="text-center text-xl font-medium text-white">
          The decentralized solution for saving your private, sensitive data
          securely.
        </p>

        <Modal btnText="Add New">
          <FormWrapper />
        </Modal>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          {links.map((link) => {
            return (
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href={link.link}
                target="_blank"
                rel="noopener noreferrer"
                key={link.id}
              >
                <h3 className="text-2xl font-bold">{link.title} →</h3>
                <div className="text-base">{link.description}</div>
              </Link>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default Home;
