import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import Modal from "../components/modal";
import { FormWrapper } from "../components/new/wrapper";
import { HOMEPAGE_LINKS as links } from "../data";

const Home: NextPage = () => {
  const [isTitleHovered, setIsTitleHovered] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <motion.h1
          onMouseEnter={() => setIsTitleHovered(true)}
          onMouseLeave={() => setIsTitleHovered(false)}
          initial={{ scale: 0, opacity: 0.1 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ ease: "easeIn" }}
          className={` gradient-underline text-center font-extrabold tracking-tight text-white transition-all duration-500 sm:text-[5rem]`}
        >
          <span className="gradient-text">
            D
            {isTitleHovered && (
              <span className=" transition-all duration-200 ease-in-out">
                entralized
              </span>
            )}
          </span>
          -Warden
        </motion.h1>

        <p className="text-center text-xl font-medium text-white">
          The decentralized solution for saving your private, sensitive data
          securely.
        </p>

        <Modal btnText="Add New">
          <FormWrapper />
        </Modal>

        <motion.div
          variants={container}
          className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"
        >
          {links.map((link) => {
            return (
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href={link.link}
                target="_blank"
                rel="noopener noreferrer"
                key={link.id}
              >
                <motion.h3 variants={item} className="text-2xl font-bold">
                  {link.title} →
                </motion.h3>
                <motion.div variants={item} className="text-base">
                  {link.description}
                </motion.div>
              </Link>
            );
          })}
        </motion.div>
      </div>
    </>
  );
};

export default Home;

// framer motion

// Links
const container = {
  hidden: { opacity: 1, scale: 0 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delayChildren: 0.3,
      staggerChildren: 0.2,
    },
  },
};

const item = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
  },
};

// Decentralized Hover
const hoverVariant = {
  initial: {
    scale: 0,
    opacity: 0.1,
  },
  animate: {
    scale: 1,
    opacity: 1,
  },
  transition: {
    ease: "easeIn",
  },
};
