import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          <span className="text-[hsl(280,100%,70%)]">D</span>-Warden
        </h1>

        <p className="text-center text-xl font-medium text-white">
          The decentralized solution for saving your private, sensitive data
          securely.
        </p>
        <button className="rounded-full border border-[hsl(280,100%,70%)] px-4 py-3 font-serif text-xl font-bold tracking-wider text-white outline-none transition-all duration-300 hover:bg-[hsl(280,100%,70%)] hover:px-6 hover:tracking-widest">
          Add New
        </button>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          {links.map((link) => {
            return (
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href={link.link}
                target="_blank"
                rel="noopener noreferrer"
                key={link.id}
              >
                <h3 className="text-2xl font-bold">{link.title} →</h3>
                <div className="text-base">{link.description}</div>
              </Link>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default Home;

const links = [
  {
    id: 1,
    title: "Passwords",
    description:
      " Stop writing down your log-in credentials, private keys on a paper.",
    link: "/add",
  },
  {
    id: 2,
    title: "Documents",
    description:
      " Be in-charge of your documents and choose who can access them.",
    link: "/add",
  },
  {
    id: 3,
    title: "Private Information",
    description:
      "Save your sensitive data securely, with no fear of data breach.",
    link: "/add",
  },
  {
    id: 4,
    title: "Card Details",
    description:
      "Don't waste time looking at your card. The session is expiring.",
    link: "/add",
  },
];
